mand-1.0: libdmconfig/dmconfig.c File Reference
dmconfig.c File Reference
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdlib.h>
#include <time.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <poll.h>
#include <fcntl.h>
#include <event.h>
#include <syslog.h>
#include <signal.h>
#include <talloc.h>
#include "dmmsg.h"
#include "codes.h"
#include "dmconfig.h"
#include "utils/logx.h"
#include "utils/binary.h"
Macros
#define debug(format,...)
#define aux_RET(STATUS, RC)
#define aux_RET_SIG(STATUS, RC)
#define CALLBACK(WHERE,...)
#define NOTIFY_CALLBACK(EVENT, GRP)
Functions
static void postprocessRequest (COMMCONTEXT *ctx)
static void connectEvent (int fd, short event, void *arg)
default connect event handler, translate from libev to connect callback
static void writeEvent (int fd, short event, void *arg)
libev write event handler,
static void readEvent (int fd, short event, void *arg)
libev read event handler,
static int process_active_notification (DMCONTEXT *dmCtx)
process notification events, invoke notify callback
static void generic_connectHandler (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__((unused)), void *userdata)
default, blocking connect handler
static void generic_answerHandler (DMCONFIG_EVENT event __attribute__((unused)), DMCONTEXT *dmCtx __attribute__((unused)), void *user_data, uint32_t answer_rc, DM_AVPGRP *answer_grp)
default, blocking answer handler
uint32_t event_aux_dmRead (int fd, short event, COMMCONTEXT *readCtx, uint8_t *alreadyRead, COMMSTATUS *status)
libev write event callback
uint32_t event_aux_dmWrite (int fd, short event, COMMCONTEXT *writeCtx, COMMSTATUS *status)
libev read event callback
void dm_free_requests (DMCONTEXT *dmCtx)
free all requests in a DMCONTEXT
uint32_t dm_register_connect_callback (DMCONTEXT *dmCtx, int type, DMCONFIG_CONNECT_CALLBACK callback, void *userdata)
start an asynchonous connect
uint32_t dm_generic_register_request (DMCONTEXT *dmCtx, uint32_t code, DM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
send an asynchonous request with a list of arguments
uint32_t dm_generic_register_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, first argument is a boolean
uint32_t dm_generic_register_request_uint32_timeouts (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, consisting of an uint32 and two timeouts
uint32_t dm_generic_register_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, only argument is a string
uint32_t dm_generic_register_request_path (DMCONTEXT *dmCtx, uint32_t code, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, only argument is a data-model path
uint32_t dm_generic_register_request_char_address (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, only argument is a IP(v4) address
uint32_t dm_init_socket (DMCONTEXT *dmCtx, int type)
create a new DM socket in a given context
uint32_t dm_generic_send_request (DMCONTEXT *dmCtx, uint32_t code, DM_AVPGRP *grp, DM_AVPGRP **ret)
Synchonous request with a list of arguments.
uint32_t dm_generic_send_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DM_AVPGRP *grp)
Synchonous compound request, first argument is a boolean.
uint32_t dm_generic_send_request_uint32_timeouts_get_grp (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DM_AVPGRP **ret)
Synchonous compound request, consisting of an uint32 and two timeouts.
uint32_t dm_generic_send_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str)
Synchonous compound request, only argument is a string.
uint32_t dm_generic_send_request_path_get_grp (DMCONTEXT *dmCtx, uint32_t code, const char *path, DM_AVPGRP **answer)
Synchonous compound request, only argument is a data-model path.
uint32_t dm_generic_send_request_path_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *path, char **data)
Synchonous compound request, only argument is a data-model path, return value is a single string.
uint32_t dm_generic_send_request_char_address_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, char **data)
Synchonous compound request, arguments are a string and an IP(v4) address.
uint32_t dm_grp_set (DM_AVPGRP **grp, const char *name, int type, void *value, size_t size)
build AVP group for SET packet
uint32_t dm_send_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t *instance)
Synchonous add instance request.
uint32_t dm_send_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DM_AVPGRP **answer)
Synchonous list request.
uint32_t dm_register_subscribe_notify (DMCONTEXT *dmCtx, DMCONFIG_ACTIVE_NOTIFY notify_callback, void *notify_callback_ud, DMCONFIG_CALLBACK callback, void *callback_ud)
Initialize a subscription to active notification.
uint32_t dm_register_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t instance, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous add an object instance.
uint32_t dm_register_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous list request.
uint32_t dm_decode_notifications (DM_AVPGRP *grp, uint32_t *type, DM_AVPGRP **notify)
process AVP group returned by dm_send|register_get_passive_notifications or received as an active notification callback parameter
uint32_t dm_decode_unknown_as_string (uint32_t type, void *data, size_t len, char **val)
converts an arbitrary typed AVP data to an ASCII string
uint32_t dm_decode_node_list (DM_AVPGRP *grp, char **name, uint32_t *type, uint32_t *size, uint32_t *datatype)
Variables
int dmconfig_debug_level
static uint32_t hopid
static uint32_t endid
Macro Definition Documentation
#define aux_RET (STATUS, RC)
Definition at line 92 of file dmconfig.c.
Referenced by event_aux_dmRead(), and event_aux_dmWrite().
#define aux_RET_SIG (STATUS, RC)
Definition at line 96 of file dmconfig.c.
Referenced by event_aux_dmWrite().
#define CALLBACK (WHERE, ...)
Definition at line 102 of file dmconfig.c.
Referenced by connectEvent(), readEvent(), and writeEvent().
#define debug (format, ...)
Definition at line 59 of file dmconfig.c.
Referenced by event_aux_dmRead().
#define NOTIFY_CALLBACK (EVENT, GRP)
Definition at line 106 of file dmconfig.c.
Referenced by process_active_notification().
Function Documentation
static void connectEvent (int fd, short event, void * arg) static
default connect event handler, translate from libev to connect callback
Definition at line 999 of file dmconfig.c.
References CALLBACK, DMCONFIG_CONNECTED, DMCONFIG_ERROR_CONNECTING, conneventCtx::dmCtx, size, and conneventCtx::user_data.
Referenced by dm_register_connect_callback().
uint32_t dm_decode_node_list (DM_AVPGRP * grp, char ** name, uint32_t * type, uint32_t * size, uint32_t * datatype)
Definition at line 1644 of file dmconfig.c.
References AVP_CONTAINER, AVP_NODE_DATATYPE, AVP_NODE_NAME, AVP_NODE_SIZE, AVP_NODE_TYPE, code, dm_avpgrp_get_avp(), dm_decode_avpgrp(), dm_get_uint32_avp(), dm_grp_free(), flags, NODE_OBJECT, NODE_PARAMETER, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
void dm_free_requests (DMCONTEXT * dmCtx) private
free all requests in a DMCONTEXT
Definition at line 267 of file dmconfig.c.
References commContext::buffer, commContext::bytes, commContext::cAlloc, commContext::event, dmContext::readCtx, commContext::req, dmContext::requestlist_head, and dmContext::writeCtx.
Referenced by dmcontext_events_gc(), and dmcontext_sequential_gc().
uint32_t event_aux_dmRead (int fd, short event, COMMCONTEXT * readCtx, uint8_t * alreadyRead, COMMSTATUS * status) private
libev write event callback
Definition at line 125 of file dmconfig.c.
References aux_RET, commContext::buffer, BUFFER_CHUNK_SIZE, commContext::bytes, commContext::cAlloc, COMPLETE, CONNRESET, debug, dm_packet_length(), ERROR, INCOMPLETE, length, NOTHING, dm_request::packet, postprocessRequest(), RC_ERR_ALLOC, RC_ERR_CONNECTION, RC_OK, and commContext::req.
Referenced by readEvent().
uint32_t event_aux_dmWrite (int fd, short event, COMMCONTEXT * writeCtx, COMMSTATUS * status) private
libev read event callback
Definition at line 218 of file dmconfig.c.
References aux_RET, aux_RET_SIG, commContext::buffer, commContext::bytes, COMPLETE, CONNRESET, ERROR, INCOMPLETE, dm_request::info, length, NOTHING, dm_request::packet, RC_ERR_CONNECTION, RC_OK, commContext::req, and dm_request_info::size.
Referenced by writeEvent().
static void generic_answerHandler (DMCONFIG_EVENT event __attribute__(unused), DMCONTEXT *dmCtx __attribute__(unused), void * user_data, uint32_t answer_rc, DM_AVPGRP * answer_grp) static
default, blocking answer handler
Definition at line 973 of file dmconfig.c.
Referenced by dm_generic_send_request().
static void generic_connectHandler (DMCONFIG_EVENT event, DMCONTEXT *dmCtx __attribute__(unused), void * userdata) static
default, blocking connect handler
return only a code
Definition at line 712 of file dmconfig.c.
References DMCONFIG_ERROR_CONNECTING, RC_ERR_CONNECTION, and RC_OK.
Referenced by dm_init_socket().
static void postprocessRequest (COMMCONTEXT * ctx) inline static
Definition at line 116 of file dmconfig.c.
References dm_request_info::avpptr, commContext::buffer, dm_packet_length(), dm_request::info, dm_request::packet, commContext::req, and dm_request_info::size.
Referenced by event_aux_dmRead().
static int process_active_notification (DMCONTEXT * dmCtx) inline static
process notification events, invoke notify callback
Definition at line 1278 of file dmconfig.c.
References dmContext::_dmContext_callbacks::active_notification, AVP_CONTAINER, dmContext::_dmContext_callbacks::_callback_active_notification::callback, dmContext::callbacks, dm_decode_avpgrp(), dm_request_get_avp(), DMCONFIG_ANSWER_READY, DMCONFIG_ERROR_READING, flags, NOTIFY_CALLBACK, dmContext::readCtx, commContext::req, and vendor_id.
static void readEvent (int fd, short event, void * arg) static
libev read event handler,
Definition at line 1114 of file dmconfig.c.
References dmContext::_dmContext_callbacks::active_notification, AVP_CONTAINER, AVP_RC, commContext::bytes, CALLBACK, dmContext::_dmContext_callbacks::_callback_active_notification::callback, dmContext::callbacks, commContext::cAlloc, CMD_ENDSESSION, CMD_FLAG_REQUEST, CMD_SUBSCRIBE_NOTIFY, CMD_UNSUBSCRIBE_NOTIFY, requestInfo::code, COMPLETE, dm_decode_avpgrp(), dm_get_uint32_avp(), dm_hop2hop_id(), dm_packet_code(), dm_packet_flags(), dm_request_get_avp(), dm_request_reset_avp(), DMCONFIG_ANSWER_READY, dmconfig_debug_level, DMCONFIG_ERROR_READING, requestInfo::dmCtx, dump_dm_packet(), commContext::event, event_aux_dmRead(), flags, hopid, requestInfo::hopid, INCOMPLETE, requestInfo::next, NOTHING, dm_request::packet, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, dmContext::readCtx, commContext::req, REQUEST_SHALL_READ, dmContext::requestlist_head, requestInfo::status, TIMEOUT_CHUNKS, TIMEOUT_READ_REQUESTS, requestInfo::user_data, and vendor_id.
Referenced by writeEvent().
static void writeEvent (int fd, short event, void * arg) static
libev write event handler,
Definition at line 1020 of file dmconfig.c.
References commContext::buffer, CALLBACK, COMPLETE, commContext::cur_request, dm_context_get_event_base(), DMCONFIG_ERROR_WRITING, requestInfo::dmCtx, commContext::event, event_aux_dmWrite(), INCOMPLETE, L_FOREACH, requestInfo::next, NOTHING, RC_ERR_ALLOC, dmContext::readCtx, readEvent(), commContext::req, requestInfo::request, REQUEST_SHALL_READ, REQUEST_SHALL_WRITE, REQUEST_WRITING, dmContext::requestlist_head, dmContext::socket, requestInfo::status, TIMEOUT_CHUNKS, TIMEOUT_READ_REQUESTS, TIMEOUT_WRITE_REQUESTS, requestInfo::user_data, and dmContext::writeCtx.
Referenced by dm_generic_register_request().
Variable Documentation
int dmconfig_debug_level
Definition at line 53 of file dmconfig.c.
Referenced by dm_generic_register_request(), LUA_SIG(), and readEvent().
uint32_t endid static
Definition at line 90 of file dmconfig.c.
Referenced by dm_generic_register_request().
uint32_t hopid static
Definition at line 89 of file dmconfig.c.
Referenced by dm_generic_register_request(), and readEvent().