mand-1.0: libdmconfig/dmmsg.c File Reference
dmmsg.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include <string.h>
#include <inttypes.h>
#include <talloc.h>
#include "errors.h"
#include "codes.h"
#include "dmmsg.h"
Functions
int get_avp (uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len, DM_AVP **avp)
DM_REQUEST * new_dm_request (void *ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
int dm_decode_request (void *ctx, DM_REQUEST **req, void *data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
int dm_add_data (DM_REQUEST *req, void *data, size_t len)
int dm_decode_complete (DM_REQUEST *req)
int build_dm_request (void *ctx, DM_REQUEST **req, DM_AVPGRP *avpgrp)
DM_AVPGRP * new_dm_avpgrp (void *ctx)
DM_AVPGRP * dm_decode_avpgrp (void *ctx, void *data, size_t len)
int dm_avpgrp_add_avpgrp (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DM_AVPGRP *source)
int dm_avpgrp_insert_raw (void *ctx, DM_AVPGRP **avpgrp, const void *data, size_t len)
int dm_avpgrp_add_raw (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void *data, size_t len)
int dm_avpgrp_add_address (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void *data)
int dm_avpgrp_add_uint32_string (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char *d2)
int dm_get_address_avp (int *af, void *addr, const void *src)
Function Documentation
int build_dm_request (void * ctx, DM_REQUEST ** req, DM_AVPGRP * avpgrp)
Definition at line 141 of file dmmsg.c.
References dm_avpgrp_info::avps_length, dm_avpgrp::info, dm_request::info, dm_request_info::size, and uint32to24().
Referenced by dm_generic_register_request().
int dm_add_data (DM_REQUEST * req, void * data, size_t len)
Definition at line 113 of file dmmsg.c.
References dm_request_info::avpptr, dm_packet_length(), dm_request::info, dm_request::packet, and dm_request_info::size.
int dm_avpgrp_add_address (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void * data)
Definition at line 259 of file dmmsg.c.
References __attribute__(), dm_avpgrp_add_raw(), IANA_INET, and IANA_INET6.
Referenced by dm_generic_register_request_char_address(), dm_generic_send_request_char_address_get_char(), and dm_grp_set_addr().
int dm_avpgrp_add_avpgrp (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DM_AVPGRP * source)
Definition at line 188 of file dmmsg.c.
References AVP_FLAG_MANDATORY, dm_avpgrp_info::avps_length, dm_avp_length(), dm_avpgrp_add_raw(), dm_avpgrp::info, and PAD32.
Referenced by dm_generic_register_request(), dm_generic_register_request_bool_grp(), dm_generic_send_request_bool_grp(), dm_grp_set(), and dm_grp_set_addr().
int dm_avpgrp_add_raw (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void * data, size_t len)
Definition at line 221 of file dmmsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_VENDOR, dm_avpgrp_info::avps_length, dm_avp::code, DM_BLOCK_ALLOC, dm_avp::flags, dm_avpgrp::info, dm_avp::length, PAD32, dm_avpgrp_info::size, uint32to24(), and dm_avp::vendor_id.
Referenced by dm_avpgrp_add_address(), dm_avpgrp_add_avpgrp(), dm_avpgrp_add_float32(), dm_avpgrp_add_float64(), dm_avpgrp_add_int32(), dm_avpgrp_add_int64(), dm_avpgrp_add_int8(), dm_avpgrp_add_string(), dm_avpgrp_add_time(), dm_avpgrp_add_timeval(), dm_avpgrp_add_uint32(), dm_avpgrp_add_uint32_string(), dm_avpgrp_add_uint64(), dm_avpgrp_add_uint8(), and dm_grp_set().
int dm_avpgrp_add_uint32_string (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char * d2)
Definition at line 283 of file dmmsg.c.
References dm_avpgrp_add_raw(), and size.
Referenced by dm_grp_get_absticks(), dm_grp_get_addr(), dm_grp_get_binary(), dm_grp_get_bool(), dm_grp_get_counter(), dm_grp_get_date(), dm_grp_get_enum(), dm_grp_get_enumid(), dm_grp_get_int32(), dm_grp_get_int64(), dm_grp_get_path(), dm_grp_get_relticks(), dm_grp_get_string(), dm_grp_get_uint32(), dm_grp_get_uint64(), dm_grp_get_unknown(), and Lua_build_get_grp().
int dm_avpgrp_insert_raw (void * ctx, DM_AVPGRP ** avpgrp, const void * data, size_t len)
Definition at line 205 of file dmmsg.c.
References dm_avpgrp_info::avps_length, DM_BLOCK_ALLOC, dm_avpgrp::info, and dm_avpgrp_info::size.
Referenced by dm_avpgrp_insert_avpgrp().
DM_AVPGRP* dm_decode_avpgrp (void * ctx, void * data, size_t len)
Definition at line 173 of file dmmsg.c.
References dm_avpgrp_info::avpptr, dm_avpgrp_info::avps_length, dm_avpgrp::info, and dm_avpgrp_info::size.
Referenced by dm_decode_container(), dm_decode_node_list(), dm_decode_notifications(), dump_avpgrp(), dump_dm_packet(), Lua_decode_list(), process_active_notification(), and readEvent().
int dm_decode_complete (DM_REQUEST * req)
Definition at line 130 of file dmmsg.c.
References dm_request_info::avpptr, dm_packet_length(), dm_request::info, dm_request::packet, and dm_request_info::size.
int dm_decode_request (void * ctx, DM_REQUEST ** req, void * data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
Parameters
ctx talloc memory context for request
req pointer to pointer to new request structure
data pointer to the data read from the network
len length of data
Returns
amount of data read form buffer
Definition at line 90 of file dmmsg.c.
References dm_packet_length().
int dm_get_address_avp (int * af, void * addr, const void * src)
Definition at line 300 of file dmmsg.c.
References IANA_INET, and IANA_INET6.
Referenced by dm_decode_addr(), and dm_decode_unknown_as_string().
int get_avp (uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len, DM_AVP ** avp)
Definition at line 31 of file dmmsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_RESERVED, AVP_FLAG_VENDOR, dm_avp_length(), DM_INVALID_AVP_BITS, DM_INVALID_AVP_LENGTH, and PAD32.
Referenced by dm_avpgrp_get_avp(), and dm_request_get_avp().
DM_AVPGRP* new_dm_avpgrp (void * ctx)
Definition at line 159 of file dmmsg.c.
References dm_avpgrp_info::avpptr, dm_avpgrp_info::avps_length, DM_BLOCK_ALLOC, dm_avpgrp::info, and dm_avpgrp_info::size.
Referenced by dm_generic_register_request(), dm_grp_new(), dm_grp_set(), and dm_grp_set_addr().
DM_REQUEST* new_dm_request (void * ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
Definition at line 59 of file dmmsg.c.
References dm_packet::app_id, dm_packet::code, dm_packet::end2end_id, dm_packet::flags, flags, dm_packet::hop2hop_id, dm_request::info, dm_request::packet, dm_request_info::size, uint32to24(), and dm_packet::version.
Referenced by dm_generic_register_request().