mand-1.0: libdmconfig/dmmsg.h File Reference
dmmsg.h File Reference
#include <arpa/inet.h>
#include <netinet/in.h>
#include <bits/byteswap.h>
#include <stdint.h>
#include <string.h>
Data Structures
struct dm_avp
struct dm_avpgrp_info
struct dm_avpgrp
struct dm_request_info
struct dm_packet
struct dm_request
struct dm_timeval
Macros
#define _GNU_SOURCE
#define IANA_INET
#define IANA_INET6
#define ntohll(x)
#define htonll(x)
#define DM_BLOCK_ALLOC
#define PAD32(x)
#define TIME_SINCE_EPOCH
#define CMD_FLAG_REQUEST
#define CMD_FLAG_PROXIABLE
#define CMD_FLAG_ERROR
#define CMD_FLAG_RETRANSMITED
#define CMD_FLAG_RESERVED
#define AVP_FLAG_VENDOR
#define AVP_FLAG_MANDATORY
#define AVP_FLAG_PRIVAT
#define AVP_FLAG_RESERVED
Typedefs
typedef struct dm_request DM_REQUEST
typedef struct dm_avp DM_AVP
typedef struct dm_avpgrp_info DM_AVPGRP_INFO
typedef struct dm_avpgrp DM_AVPGRP
typedef struct dm_request_info DM_REQUEST_INFO
typedef struct dm_packet DM_PACKET
typedef struct dm_request_head DM_REQUEST_HEAD
typedef struct dm_timeval DM_TIMEVAL
Functions
struct dm_avp __attribute__ ((packed))
int get_avp (uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len, DM_AVP **src)
DM_REQUEST * new_dm_request (void *ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
int dm_decode_request (void *ctx, DM_REQUEST **req, void *data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
int dm_add_data (DM_REQUEST *req, void *data, size_t len)
int dm_decode_complete (DM_REQUEST *req)
int build_dm_request (void *ctx, DM_REQUEST **req, DM_AVPGRP *avpgrp)
DM_AVPGRP * new_dm_avpgrp (void *ctx)
DM_AVPGRP * dm_decode_avpgrp (void *ctx, void *data, size_t len)
int dm_avpgrp_add_avpgrp (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DM_AVPGRP *source)
int dm_avpgrp_insert_raw (void *ctx, DM_AVPGRP **avpgrp, const void *data, size_t len)
int dm_avpgrp_add_raw (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void *data, size_t len)
int dm_avpgrp_add_address (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void *data)
int dm_avpgrp_add_uint32_string (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char *d2)
int dm_get_address_avp (int *af, void *addr, const void *src)
static uint32_t uint24to32 (uint8_t i24[3])
static void uint32to24 (uint8_t i24[3], uint32_t i32)
static uint8_t dm_packet_flags (DM_PACKET *pkt)
static uint32_t dm_packet_length (DM_PACKET *pkt)
static uint32_t dm_packet_code (DM_PACKET *pkt)
static uint32_t dm_app_id (DM_PACKET *pkt)
static uint32_t dm_end2end_id (DM_PACKET *pkt)
static uint32_t dm_hop2hop_id (DM_PACKET *pkt)
static uint32_t dm_avp_length (DM_AVP *avp)
static void dm_request_reset_avp (DM_REQUEST *req)
static int dm_request_get_avp (DM_REQUEST *req, uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len)
static void dm_avpgrp_reset_avp (DM_AVPGRP *avpgrp)
static int dm_avpgrp_get_avp (DM_AVPGRP *avpgrp, uint32_t *code, uint8_t *flags, uint32_t *vendor_id, void **data, size_t *len)
static int dm_avpgrp_add_string (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const char *data)
static int dm_avpgrp_add_int8 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int8_t data)
static int dm_avpgrp_add_uint8 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint8_t data)
static int dm_avpgrp_add_int16 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int16_t data)
static int dm_avpgrp_add_uint16 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint16_t data)
static int dm_avpgrp_add_int32 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int32_t data)
static int dm_avpgrp_add_uint32 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t data)
static int dm_avpgrp_add_uint64 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint64_t data)
static int dm_avpgrp_add_int64 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int64_t data)
static int dm_avpgrp_add_float32 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, float data)
static int dm_avpgrp_add_float64 (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, double data)
static int dm_avpgrp_add_time (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, time_t data)
static int dm_avpgrp_add_timeval (void *ctx, DM_AVPGRP **avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, struct timeval value)
static int dm_avpgrp_insert_avpgrp (void *ctx, DM_AVPGRP **avpgrp, DM_AVPGRP *source)
static int dm_get_string_avp (char *dest, size_t dlen, const void *src, size_t slen)
static int8_t dm_get_int8_avp (const void *src)
static uint8_t dm_get_uint8_avp (const void *src)
static int16_t dm_get_int16_avp (const void *src)
static uint16_t dm_get_uint16_avp (const void *src)
static int32_t dm_get_int32_avp (const void *src)
static uint32_t dm_get_uint32_avp (const void *src)
static int64_t dm_get_int64_avp (const void *src)
static uint64_t dm_get_uint64_avp (const void *src)
static time_t dm_get_time_avp (const void *src)
static struct timeval dm_get_timeval_avp (const void *src)
Variables
uint32_t code
uint8_t flags
uint8_t length [3]
uint32_t vendor_id
DM_AVP * avpptr
uint32_t size
uint32_t avps_length
DM_AVPGRP_INFO info
DM_REQUEST * next
uint8_t version
uint32_t app_id
uint32_t hop2hop_id
uint32_t end2end_id
DM_PACKET packet
uint32_t tv_sec
uint32_t tv_usec
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 9 of file dmmsg.h.
#define AVP_FLAG_MANDATORY
Definition at line 107 of file dmmsg.h.
Referenced by dm_avpgrp_add_avpgrp(), dm_avpgrp_add_raw(), and get_avp().
#define AVP_FLAG_PRIVAT
Definition at line 108 of file dmmsg.h.
Referenced by dm_avpgrp_add_raw(), and get_avp().
#define AVP_FLAG_RESERVED
Definition at line 109 of file dmmsg.h.
Referenced by get_avp().
#define AVP_FLAG_VENDOR
Definition at line 106 of file dmmsg.h.
Referenced by dm_avpgrp_add_raw(), and get_avp().
#define CMD_FLAG_ERROR
Definition at line 100 of file dmmsg.h.
#define CMD_FLAG_PROXIABLE
Definition at line 99 of file dmmsg.h.
#define CMD_FLAG_REQUEST
Definition at line 98 of file dmmsg.h.
Referenced by dm_generic_register_request(), and readEvent().
#define CMD_FLAG_RESERVED
Definition at line 102 of file dmmsg.h.
#define CMD_FLAG_RETRANSMITED
Definition at line 101 of file dmmsg.h.
#define DM_BLOCK_ALLOC
Definition at line 33 of file dmmsg.h.
Referenced by dm_avpgrp_add_raw(), dm_avpgrp_insert_raw(), and new_dm_avpgrp().
#define htonll (x)
Definition at line 25 of file dmmsg.h.
Referenced by dm_avpgrp_add_int64(), dm_avpgrp_add_uint64(), dm_grp_set_absticks(), dm_grp_set_int64(), dm_grp_set_relticks(), dm_grp_set_uint64(), and Lua_encode_value().
#define IANA_INET
Definition at line 18 of file dmmsg.h.
Referenced by dm_avpgrp_add_address(), and dm_get_address_avp().
#define IANA_INET6
Definition at line 19 of file dmmsg.h.
Referenced by dm_avpgrp_add_address(), and dm_get_address_avp().
#define ntohll (x)
Definition at line 24 of file dmmsg.h.
Referenced by dm_get_int64_avp(), and dm_get_uint64_avp().
#define PAD32 (x)
Definition at line 35 of file dmmsg.h.
Referenced by dm_avpgrp_add_avpgrp(), dm_avpgrp_add_raw(), and get_avp().
#define TIME_SINCE_EPOCH
Definition at line 37 of file dmmsg.h.
Referenced by dm_avpgrp_add_time(), and dm_get_time_avp().
Typedef Documentation
typedef struct dm_avp DM_AVP
Definition at line 41 of file dmmsg.h.
typedef struct dm_avpgrp DM_AVPGRP
Definition at line 43 of file dmmsg.h.
typedef struct dm_avpgrp_info DM_AVPGRP_INFO
Definition at line 42 of file dmmsg.h.
typedef struct dm_packet DM_PACKET
Definition at line 45 of file dmmsg.h.
typedef struct dm_request DM_REQUEST
Definition at line 40 of file dmmsg.h.
typedef struct dm_request_head DM_REQUEST_HEAD
Definition at line 46 of file dmmsg.h.
typedef struct dm_request_info DM_REQUEST_INFO
Definition at line 44 of file dmmsg.h.
typedef struct dm_timeval DM_TIMEVAL
Definition at line 47 of file dmmsg.h.
Function Documentation
struct dm_timeval __attribute__ ((packed))
Referenced by dm_avpgrp_add_address().
int build_dm_request (void * ctx, DM_REQUEST ** req, DM_AVPGRP * avpgrp)
Definition at line 141 of file dmmsg.c.
References dm_avpgrp_info::avps_length, dm_avpgrp::info, dm_request::info, dm_request_info::size, and uint32to24().
Referenced by dm_generic_register_request().
int dm_add_data (DM_REQUEST * req, void * data, size_t len)
Definition at line 113 of file dmmsg.c.
References dm_request_info::avpptr, dm_packet_length(), dm_request::info, dm_request::packet, and dm_request_info::size.
static uint32_t dm_app_id (DM_PACKET * pkt) inline static
Definition at line 229 of file dmmsg.h.
References dm_packet::app_id.
static uint32_t dm_avp_length (DM_AVP * avp) inline static
Definition at line 244 of file dmmsg.h.
References dm_avp::length, and uint24to32().
Referenced by dm_avpgrp_add_avpgrp(), and get_avp().
int dm_avpgrp_add_address (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int af, const void * data)
Definition at line 259 of file dmmsg.c.
References __attribute__(), dm_avpgrp_add_raw(), IANA_INET, and IANA_INET6.
Referenced by dm_generic_register_request_char_address(), dm_generic_send_request_char_address_get_char(), and dm_grp_set_addr().
int dm_avpgrp_add_avpgrp (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, DM_AVPGRP * source)
Definition at line 188 of file dmmsg.c.
References AVP_FLAG_MANDATORY, dm_avpgrp_info::avps_length, dm_avp_length(), dm_avpgrp_add_raw(), dm_avpgrp::info, and PAD32.
Referenced by dm_generic_register_request(), dm_generic_register_request_bool_grp(), dm_generic_send_request_bool_grp(), dm_grp_set(), and dm_grp_set_addr().
static int dm_avpgrp_add_float32 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, float data) inline static
Definition at line 352 of file dmmsg.h.
References dm_avpgrp_add_raw().
static int dm_avpgrp_add_float64 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, double data) inline static
Definition at line 359 of file dmmsg.h.
References dm_avpgrp_add_raw().
static int dm_avpgrp_add_int16 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int16_t data) inline static
Definition at line 298 of file dmmsg.h.
static int dm_avpgrp_add_int32 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int32_t data) inline static
Definition at line 316 of file dmmsg.h.
References dm_avpgrp_add_raw().
static int dm_avpgrp_add_int64 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int64_t data) inline static
Definition at line 343 of file dmmsg.h.
References dm_avpgrp_add_raw(), and htonll.
static int dm_avpgrp_add_int8 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, int8_t data) inline static
Definition at line 284 of file dmmsg.h.
References dm_avpgrp_add_raw().
int dm_avpgrp_add_raw (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const void * data, size_t len)
Definition at line 221 of file dmmsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_VENDOR, dm_avpgrp_info::avps_length, dm_avp::code, DM_BLOCK_ALLOC, dm_avp::flags, dm_avpgrp::info, dm_avp::length, PAD32, dm_avpgrp_info::size, uint32to24(), and dm_avp::vendor_id.
Referenced by dm_avpgrp_add_address(), dm_avpgrp_add_avpgrp(), dm_avpgrp_add_float32(), dm_avpgrp_add_float64(), dm_avpgrp_add_int32(), dm_avpgrp_add_int64(), dm_avpgrp_add_int8(), dm_avpgrp_add_string(), dm_avpgrp_add_time(), dm_avpgrp_add_timeval(), dm_avpgrp_add_uint32(), dm_avpgrp_add_uint32_string(), dm_avpgrp_add_uint64(), dm_avpgrp_add_uint8(), and dm_grp_set().
static int dm_avpgrp_add_string (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, const char * data) inline static
Definition at line 277 of file dmmsg.h.
References dm_avpgrp_add_raw().
Referenced by dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_grp_param_notify(), dm_grp_set(), dm_grp_set_addr(), dm_register_add_instance(), dm_register_find_instance(), dm_register_list(), dm_register_recursive_param_notify(), dm_send_add_instance(), dm_send_find_instance(), dm_send_list(), and dm_send_recursive_param_notify().
static int dm_avpgrp_add_time (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, time_t data) inline static
Definition at line 366 of file dmmsg.h.
References dm_avpgrp_add_raw(), and TIME_SINCE_EPOCH.
static int dm_avpgrp_add_timeval (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, struct timeval value) inline static
Definition at line 380 of file dmmsg.h.
References dm_avpgrp_add_raw(), dm_timeval::tv_sec, and dm_timeval::tv_usec.
Referenced by dm_generic_register_request_uint32_timeouts(), and dm_generic_send_request_uint32_timeouts_get_grp().
static int dm_avpgrp_add_uint16 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint16_t data) inline static
Definition at line 307 of file dmmsg.h.
Referenced by dm_register_add_instance(), dm_register_list(), dm_send_add_instance(), and dm_send_list().
static int dm_avpgrp_add_uint32 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t data) inline static
Definition at line 325 of file dmmsg.h.
References dm_avpgrp_add_raw().
Referenced by dm_generic_register_request(), dm_generic_register_request_uint32_timeouts(), and dm_generic_send_request_uint32_timeouts_get_grp().
int dm_avpgrp_add_uint32_string (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint32_t d1, const char * d2)
Definition at line 283 of file dmmsg.c.
References dm_avpgrp_add_raw(), and size.
Referenced by dm_grp_get_absticks(), dm_grp_get_addr(), dm_grp_get_binary(), dm_grp_get_bool(), dm_grp_get_counter(), dm_grp_get_date(), dm_grp_get_enum(), dm_grp_get_enumid(), dm_grp_get_int32(), dm_grp_get_int64(), dm_grp_get_path(), dm_grp_get_relticks(), dm_grp_get_string(), dm_grp_get_uint32(), dm_grp_get_uint64(), dm_grp_get_unknown(), and Lua_build_get_grp().
static int dm_avpgrp_add_uint64 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint64_t data) inline static
Definition at line 334 of file dmmsg.h.
References dm_avpgrp_add_raw(), and htonll.
static int dm_avpgrp_add_uint8 (void * ctx, DM_AVPGRP ** avpgrp, uint32_t code, uint8_t flags, uint32_t vendor_id, uint8_t data) inline static
Definition at line 291 of file dmmsg.h.
References dm_avpgrp_add_raw().
Referenced by dm_generic_register_request_bool_grp(), and dm_generic_send_request_bool_grp().
static int dm_avpgrp_get_avp (DM_AVPGRP * avpgrp, uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len) inline static
Definition at line 269 of file dmmsg.h.
References dm_avpgrp_info::avpptr, dm_avpgrp_info::avps_length, get_avp(), and dm_avpgrp::info.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_decode_unknown(), dump_avpgrp(), Lua_decode_get(), Lua_decode_list(), and Lua_decode_notifications().
static int dm_avpgrp_insert_avpgrp (void * ctx, DM_AVPGRP ** avpgrp, DM_AVPGRP * source) inline static
Definition at line 395 of file dmmsg.h.
References dm_avpgrp_info::avps_length, dm_avpgrp_insert_raw(), and dm_avpgrp::info.
int dm_avpgrp_insert_raw (void * ctx, DM_AVPGRP ** avpgrp, const void * data, size_t len)
Definition at line 205 of file dmmsg.c.
References dm_avpgrp_info::avps_length, DM_BLOCK_ALLOC, dm_avpgrp::info, and dm_avpgrp_info::size.
Referenced by dm_avpgrp_insert_avpgrp().
static void dm_avpgrp_reset_avp (DM_AVPGRP * avpgrp) inline static
Definition at line 264 of file dmmsg.h.
References dm_avpgrp_info::avpptr, and dm_avpgrp::info.
Referenced by dm_decode_reset().
DM_AVPGRP* dm_decode_avpgrp (void * ctx, void * data, size_t len)
Definition at line 173 of file dmmsg.c.
References dm_avpgrp_info::avpptr, dm_avpgrp_info::avps_length, dm_avpgrp::info, and dm_avpgrp_info::size.
Referenced by dm_decode_container(), dm_decode_node_list(), dm_decode_notifications(), dump_avpgrp(), dump_dm_packet(), Lua_decode_list(), process_active_notification(), and readEvent().
int dm_decode_complete (DM_REQUEST * req)
Definition at line 130 of file dmmsg.c.
References dm_request_info::avpptr, dm_packet_length(), dm_request::info, dm_request::packet, and dm_request_info::size.
int dm_decode_request (void * ctx, DM_REQUEST ** req, void * data, size_t len)
start decoding a request received from the network minimum lenght of received data if 4 bytes
Parameters
ctx talloc memory context for request
req pointer to pointer to new request structure
data pointer to the data read from the network
len length of data
Returns
amount of data read form buffer
Definition at line 90 of file dmmsg.c.
References dm_packet_length().
static uint32_t dm_end2end_id (DM_PACKET * pkt) inline static
Definition at line 234 of file dmmsg.h.
References dm_packet::end2end_id.
int dm_get_address_avp (int * af, void * addr, const void * src)
Definition at line 300 of file dmmsg.c.
References IANA_INET, and IANA_INET6.
Referenced by dm_decode_addr(), and dm_decode_unknown_as_string().
static int16_t dm_get_int16_avp (const void * src) inline static
Definition at line 423 of file dmmsg.h.
static int32_t dm_get_int32_avp (const void * src) inline static
Definition at line 433 of file dmmsg.h.
Referenced by dm_decode_enumid(), dm_decode_int32(), and dm_decode_unknown_as_string().
static int64_t dm_get_int64_avp (const void * src) inline static
Definition at line 443 of file dmmsg.h.
References ntohll.
Referenced by dm_decode_absticks(), dm_decode_int64(), dm_decode_relticks(), and dm_decode_unknown_as_string().
static int8_t dm_get_int8_avp (const void * src) inline static
Definition at line 413 of file dmmsg.h.
static int dm_get_string_avp (char * dest, size_t dlen, const void * src, size_t slen) inline static
Definition at line 400 of file dmmsg.h.
static time_t dm_get_time_avp (const void * src) inline static
Definition at line 453 of file dmmsg.h.
References dm_get_uint32_avp(), and TIME_SINCE_EPOCH.
Referenced by dm_decode_date(), and dm_decode_unknown_as_string().
static struct timeval dm_get_timeval_avp (const void * src) static
Definition at line 460 of file dmmsg.h.
References dm_timeval::tv_sec, and dm_timeval::tv_usec.
Referenced by dm_decode_timeval().
static uint16_t dm_get_uint16_avp (const void * src) inline static
Definition at line 428 of file dmmsg.h.
Referenced by dm_decode_uint16().
static uint32_t dm_get_uint32_avp (const void * src) inline static
Definition at line 438 of file dmmsg.h.
Referenced by dm_decode_counter(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_sessionid(), dm_decode_type_path(), dm_decode_uint32(), dm_decode_unknown_as_string(), dm_get_time_avp(), Lua_decode_list(), and readEvent().
static uint64_t dm_get_uint64_avp (const void * src) inline static
Definition at line 448 of file dmmsg.h.
References ntohll.
Referenced by dm_decode_uint64(), and dm_decode_unknown_as_string().
static uint8_t dm_get_uint8_avp (const void * src) inline static
Definition at line 418 of file dmmsg.h.
Referenced by dm_decode_bool(), and dm_decode_unknown_as_string().
static uint32_t dm_hop2hop_id (DM_PACKET * pkt) inline static
Definition at line 239 of file dmmsg.h.
References dm_packet::hop2hop_id.
Referenced by readEvent().
static uint32_t dm_packet_code (DM_PACKET * pkt) inline static
Definition at line 224 of file dmmsg.h.
References dm_packet::code, and uint24to32().
Referenced by dump_dm_packet(), and readEvent().
static uint8_t dm_packet_flags (DM_PACKET * pkt) inline static
Definition at line 214 of file dmmsg.h.
References dm_packet::flags.
Referenced by readEvent().
static uint32_t dm_packet_length (DM_PACKET * pkt) inline static
Definition at line 219 of file dmmsg.h.
References dm_packet::length, and uint24to32().
Referenced by dm_add_data(), dm_decode_complete(), dm_decode_request(), dump_dm_packet(), event_aux_dmRead(), and postprocessRequest().
static int dm_request_get_avp (DM_REQUEST * req, uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len) inline static
Definition at line 256 of file dmmsg.h.
References dm_request_info::avpptr, get_avp(), dm_request::info, and dm_request_info::size.
Referenced by dump_dm_packet(), process_active_notification(), and readEvent().
static void dm_request_reset_avp (DM_REQUEST * req) inline static
Definition at line 251 of file dmmsg.h.
References dm_request_info::avpptr, and dm_request::info.
Referenced by dump_dm_packet(), and readEvent().
int get_avp (uint32_t * code, uint8_t * flags, uint32_t * vendor_id, void ** data, size_t * len, DM_AVP ** src)
Definition at line 31 of file dmmsg.c.
References AVP_FLAG_MANDATORY, AVP_FLAG_PRIVAT, AVP_FLAG_RESERVED, AVP_FLAG_VENDOR, dm_avp_length(), DM_INVALID_AVP_BITS, DM_INVALID_AVP_LENGTH, and PAD32.
Referenced by dm_avpgrp_get_avp(), and dm_request_get_avp().
DM_AVPGRP* new_dm_avpgrp (void * ctx)
Definition at line 159 of file dmmsg.c.
References dm_avpgrp_info::avpptr, dm_avpgrp_info::avps_length, DM_BLOCK_ALLOC, dm_avpgrp::info, and dm_avpgrp_info::size.
Referenced by dm_generic_register_request(), dm_grp_new(), dm_grp_set(), and dm_grp_set_addr().
DM_REQUEST* new_dm_request (void * ctx, uint32_t code, uint8_t flags, uint32_t appid, uint32_t hopid, uint32_t endid)
Definition at line 59 of file dmmsg.c.
References dm_packet::app_id, dm_packet::code, dm_packet::end2end_id, dm_packet::flags, flags, dm_packet::hop2hop_id, dm_request::info, dm_request::packet, dm_request_info::size, uint32to24(), and dm_packet::version.
Referenced by dm_generic_register_request().
static uint32_t uint24to32 (uint8_t i24[3]) inline static
Definition at line 202 of file dmmsg.h.
Referenced by dm_avp_length(), dm_packet_code(), and dm_packet_length().
static void uint32to24 (uint8_t i24[3], uint32_t i32) inline static
Definition at line 207 of file dmmsg.h.
Referenced by build_dm_request(), dm_avpgrp_add_raw(), and new_dm_request().
Variable Documentation
uint32_t app_id
Definition at line 305 of file dmmsg.h.
DM_AVP * avpptr
Definition at line 301 of file dmmsg.h.
uint32_t avps_length
Definition at line 303 of file dmmsg.h.
uint8_t code
Definition at line 301 of file dmmsg.h.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_generic_register_request(), dump_avpgrp(), dump_dm_packet(), Lua_decode_list(), and Lua_register_eval().
uint32_t end2end_id
Definition at line 307 of file dmmsg.h.
uint8_t flags
Definition at line 302 of file dmmsg.h.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_decode_unknown(), dm_register_connect_callback(), dump_avpgrp(), dump_dm_packet(), generic_Lua_callback(), Lua_decode_get(), Lua_decode_get_session_info(), Lua_decode_list(), Lua_decode_notifications(), LUA_SIG(), LUA_SIG_REGISTER(), new_dm_request(), process_active_notification(), and readEvent().
uint32_t hop2hop_id
Definition at line 306 of file dmmsg.h.
DM_REQUEST_INFO info
Definition at line 301 of file dmmsg.h.
uint8_t length
Definition at line 303 of file dmmsg.h.
Referenced by event_aux_dmRead(), and event_aux_dmWrite().
DM_REQUEST* next
Definition at line 301 of file dmmsg.h.
DM_PACKET packet
Definition at line 302 of file dmmsg.h.
Referenced by dump_dm_packet().
uint32_t size
Definition at line 302 of file dmmsg.h.
Referenced by connectEvent(), and dm_avpgrp_add_uint32_string().
uint32_t tv_sec
Definition at line 301 of file dmmsg.h.
uint32_t tv_usec
Definition at line 302 of file dmmsg.h.
uint32_t vendor_id
Definition at line 304 of file dmmsg.h.
Referenced by dm_decode_absticks(), dm_decode_addr(), dm_decode_binary(), dm_decode_bool(), dm_decode_container(), dm_decode_counter(), dm_decode_date(), dm_decode_enum(), dm_decode_enumid(), dm_decode_int32(), dm_decode_int64(), dm_decode_node_list(), dm_decode_notifications(), dm_decode_path(), dm_decode_relticks(), dm_decode_sessionid(), dm_decode_string(), dm_decode_timeval(), dm_decode_type_path(), dm_decode_uint16(), dm_decode_uint32(), dm_decode_uint64(), dm_decode_unknown(), dump_avpgrp(), dump_dm_packet(), Lua_decode_get(), Lua_decode_list(), Lua_decode_notifications(), process_active_notification(), and readEvent().
uint8_t version
Definition at line 301 of file dmmsg.h.