mand-1.0: API
API
This is the user visible API.
Functions
uint32_t dm_register_connect_callback (DMCONTEXT *dmCtx, int type, DMCONFIG_CONNECT_CALLBACK callback, void *userdata)
start an asynchonous connect
uint32_t dm_generic_register_request (DMCONTEXT *dmCtx, uint32_t code, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
send an asynchonous request with a list of arguments
uint32_t dm_generic_register_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, first argument is a boolean
uint32_t dm_generic_register_request_uint32_timeouts (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, consisting of an uint32 and two timeouts
uint32_t dm_generic_register_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, only argument is a string
uint32_t dm_generic_register_request_path (DMCONTEXT *dmCtx, uint32_t code, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, only argument is a data-model path
uint32_t dm_generic_register_request_char_address (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, DMCONFIG_CALLBACK callback, void *callback_ud)
send an compound asynchonous request, only argument is a IP(v4) address
uint32_t dm_init_socket (DMCONTEXT *dmCtx, int type)
create a new DM socket in a given context
uint32_t dm_generic_send_request (DMCONTEXT *dmCtx, uint32_t code, DIAM_AVPGRP *grp, DIAM_AVPGRP **ret)
Synchonous request with a list of arguments.
uint32_t dm_generic_send_request_bool_grp (DMCONTEXT *dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP *grp)
Synchonous compound request, first argument is a boolean.
uint32_t dm_generic_send_request_uint32_timeouts_get_grp (DMCONTEXT *dmCtx, uint32_t code, uint32_t val, struct timeval *timeval1, struct timeval *timeval2, DIAM_AVPGRP **ret)
Synchonous compound request, consisting of an uint32 and two timeouts.
uint32_t dm_generic_send_request_string (DMCONTEXT *dmCtx, uint32_t code, const char *str)
Synchonous compound request, only argument is a string.
uint32_t dm_generic_send_request_path_get_grp (DMCONTEXT *dmCtx, uint32_t code, const char *path, DIAM_AVPGRP **answer)
Synchonous compound request, only argument is a data-model path.
uint32_t dm_generic_send_request_path_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *path, char **data)
Synchonous compound request, only argument is a data-model path, return value is a single string.
uint32_t dm_generic_send_request_char_address_get_char (DMCONTEXT *dmCtx, uint32_t code, const char *str, struct in_addr addr, char **data)
Synchonous compound request, arguments are a string and an IP(v4) address.
uint32_t dm_grp_set (DIAM_AVPGRP **grp, const char *name, int type, void *value, size_t size)
build AVP group for SET packet
uint32_t dm_send_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t *instance)
Synchonous add instance request.
uint32_t dm_send_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DIAM_AVPGRP **answer)
Synchonous list request.
uint32_t dm_register_subscribe_notify (DMCONTEXT *dmCtx, DMCONFIG_ACTIVE_NOTIFY notify_callback, void *notify_callback_ud, DMCONFIG_CALLBACK callback, void *callback_ud)
Initialize a subscription to active notification.
uint32_t dm_register_add_instance (DMCONTEXT *dmCtx, const char *path, uint16_t instance, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous add an object instance.
uint32_t dm_register_list (DMCONTEXT *dmCtx, const char *name, uint16_t level, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous list request.
uint32_t dm_decode_notifications (DIAM_AVPGRP *grp, uint32_t *type, DIAM_AVPGRP **notify)
process AVP group returned by dm_send|register_get_passive_notifications or received as an active notification callback parameter
uint32_t dm_decode_unknown_as_string (uint32_t type, void *data, size_t len, char **val)
converts an arbitrary typed AVP data to an ASCII string
static DIAM_AVPGRP * dm_grp_new (void)
allocate new AVP group
static void dm_grp_free (DIAM_AVPGRP *grp)
free AVP group
static uint32_t dm_grp_get_bool (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET boolean packet
static uint32_t dm_grp_get_int32 (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET Int32 packet
static uint32_t dm_grp_get_uint32 (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET UInt32 packet
static uint32_t dm_grp_get_int64 (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET Int64 packet
static uint32_t dm_grp_get_uint64 (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET UInt64 packet
static uint32_t dm_grp_get_counter (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET counter packet
static uint32_t dm_grp_get_enumid (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET emun id packet
static uint32_t dm_grp_get_enum (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET enum packet
static uint32_t dm_grp_get_string (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET string packet
static uint32_t dm_grp_get_addr (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET IP(v4)address packet
static uint32_t dm_grp_get_date (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET date packet
static uint32_t dm_grp_get_absticks (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET absticks packet
static uint32_t dm_grp_get_relticks (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET relticks packet
static uint32_t dm_grp_get_path (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET path packet
static uint32_t dm_grp_get_binary (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET binary packet
static uint32_t dm_grp_get_unknown (DIAM_AVPGRP **grp, const char *name)
build AVP group for GET any packet
static uint32_t dm_grp_set_bool (DIAM_AVPGRP **grp, const char *name, uint8_t value)
build AVP group for SET boolean packet
static uint32_t dm_grp_set_int32 (DIAM_AVPGRP **grp, const char *name, int32_t value)
build AVP group for SET Int32 packet
static uint32_t dm_grp_set_uint32 (DIAM_AVPGRP **grp, const char *name, uint32_t value)
build AVP group for SET UInt32 packet
static uint32_t dm_grp_set_int64 (DIAM_AVPGRP **grp, const char *name, int64_t value)
build AVP group for SET Int64 packet
static uint32_t dm_grp_set_uint64 (DIAM_AVPGRP **grp, const char *name, uint64_t value)
build AVP group for SET UInt64 packet
static uint32_t dm_grp_set_enumid (DIAM_AVPGRP **grp, const char *name, int32_t value)
build AVP group for SET enum id packet
static uint32_t dm_grp_set_enum (DIAM_AVPGRP **grp, const char *name, const char *value)
build AVP group for SET enum packet
static uint32_t dm_grp_set_string (DIAM_AVPGRP **grp, const char *name, const char *value)
build AVP group for SET string packet
static uint32_t dm_grp_set_addr (DIAM_AVPGRP **grp, const char *name, struct in_addr addr)
build AVP group for SET IP(v4) address packet
static uint32_t dm_grp_set_date (DIAM_AVPGRP **grp, const char *name, time_t value)
build AVP group for SET date packet
static uint32_t dm_grp_set_absticks (DIAM_AVPGRP **grp, const char *name, int64_t value)
build AVP group for SET absticks packet
static uint32_t dm_grp_set_relticks (DIAM_AVPGRP **grp, const char *name, int64_t value)
build AVP group for SET relticks packet
static uint32_t dm_grp_set_path (DIAM_AVPGRP **grp, const char *name, const char *path)
build AVP group for SET path packet
static uint32_t dm_grp_set_binary (DIAM_AVPGRP **grp, const char *name, void *data, size_t len)
build AVP group for SET binary packet
static uint32_t dm_grp_set_unknown (DIAM_AVPGRP **grp, const char *name, const char *value)
build AVP group for SET any packet
static uint32_t dm_grp_param_notify (DIAM_AVPGRP **grp, const char *name)
build AVP group for param notify packets
static void dm_context_init (DMCONTEXT *dmCtx, struct event_base *base)
initialize a new socket context
static DMCONTEXT * dm_context_new (void *ctx, struct event_base *base)
allocate and initialize a new socket context
static void dm_context_free (DMCONTEXT *dmCtx)
free a socket context
static void dm_context_set_socket (DMCONTEXT *dmCtx, int socket)
set the socket in a socket context
static int dm_context_get_socket (DMCONTEXT *dmCtx)
get the socket from a socket context
static void dm_context_set_sessionid (DMCONTEXT *dmCtx, uint32_t sessionid)
set the session id in a socket context
static uint32_t dm_context_get_sessionid (DMCONTEXT *dmCtx)
get the session id from a socket context
static void dm_context_set_event_base (DMCONTEXT *dmCtx, struct event_base *base)
set libev's libevent compatiblity event_base in a socket context
static struct event_base * dm_context_get_event_base (DMCONTEXT *dmCtx)
get libev's libevent compatiblity event_base from a socket context
static void dm_context_set_ev_loop (DMCONTEXT *dmCtx, struct ev_loop *loop)
set libev's ev_loop in a socket context
static struct ev_loop * dm_context_get_ev_loop (DMCONTEXT *dmCtx)
get libev's ev_loop from a socket context
static uint32_t dm_create_socket (DMCONTEXT *dmCtx, int type)
create a socket in a socket context
static void dm_shutdown_socket (DMCONTEXT *dmCtx)
shut down the socket in a socket context
static uint32_t dm_send_start_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request)
Synchonous start session request.
static uint32_t dm_send_switch_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request)
Synchonous switch session request.
static uint32_t dm_send_get_session_info (DMCONTEXT *dmCtx, uint32_t *flags)
Synchonous get session info request.
static uint32_t dm_send_get_cfg_session_info (DMCONTEXT *dmCtx, uint32_t *sessionid, uint32_t *flags, struct timeval *timeout)
Synchonous get config session info request.
static uint32_t dm_send_del_instance (DMCONTEXT *dmCtx, const char *path)
Synchonous delete instance request.
static uint32_t dm_send_find_instance (DMCONTEXT *dmCtx, const char *path, DIAM_AVPGRP *grp, uint16_t *inst)
Synchonous find instance request.
static uint32_t dm_send_retrieve_enums (DMCONTEXT *dmCtx, const char *name, DIAM_AVPGRP **answer)
Synchonous retrieve enums request.
static uint32_t dm_send_subscribe_notify (DMCONTEXT *dmCtx)
Synchonous subscribe to notifications request.
static uint32_t dm_send_recursive_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify __attribute__((unused)),const char *path)
Synchonous set notification on parameters and all child parameters.
static uint32_t dm_send_packet_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify __attribute__((unused)),DIAM_AVPGRP *grp)
Synchonous set notification on a parameter.
static uint32_t dm_send_get_passive_notifications (DMCONTEXT *dmCtx, DIAM_AVPGRP **answer)
Synchonous retrieve all pending passive notifications.
static uint32_t dm_send_unsubscribe_notify (DMCONTEXT *dmCtx)
Synchonous unsubscribe from all notifications request.
static uint32_t dm_send_end_session (DMCONTEXT *dmCtx)
Synchonous send session end request.
static uint32_t dm_send_packet_set (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp)
Synchonous send set end request.
static uint32_t dm_send_packet_get (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp, DIAM_AVPGRP **answer)
Synchonous send get end request.
static uint32_t dm_send_commit (DMCONTEXT *dmCtx)
Synchonous send commit request.
static uint32_t dm_send_cancel (DMCONTEXT *dmCtx)
Synchonous send cancel request.
static uint32_t dm_send_save (DMCONTEXT *dmCtx)
Synchonous send save request.
static uint32_t dm_send_cmd_dump (DMCONTEXT *dmCtx, const char *path, char **data)
Synchonous send dump request.
static uint32_t dm_register_start_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous start session request.
static uint32_t dm_register_switch_session (DMCONTEXT *dmCtx, uint32_t flags, struct timeval *timeout_session, struct timeval *timeout_request, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous switch session request.
static uint32_t dm_register_get_session_info (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous get session info request.
static uint32_t dm_register_get_cfg_session_info (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous get config session info request.
static uint32_t dm_register_del_instance (DMCONTEXT *dmCtx, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous delete instance request.
static uint32_t dm_register_find_instance (DMCONTEXT *dmCtx, const char *path, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous find instance request.
static uint32_t dm_register_retrieve_enums (DMCONTEXT *dmCtx, const char *name, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous retrieve enums request.
static uint32_t dm_register_unsubscribe_notify (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous unsubscribe from all notifications request.
static uint32_t dm_register_recursive_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous set notification on parameters and all child parameters.
static uint32_t dm_register_packet_param_notify (DMCONTEXT *dmCtx, uint8_t isActiveNotify, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous set notification on a parameter.
static uint32_t dm_register_get_passive_notifications (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous retrieve all pending passive notifications.
static uint32_t dm_register_end_session (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous send session end request.
static uint32_t dm_register_packet_set (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous send set end request.
static uint32_t dm_register_packet_get (DMCONTEXT *dmCtx, DIAM_AVPGRP *grp, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous send get end request.
static uint32_t dm_register_commit (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous send commit request.
static uint32_t dm_register_cancel (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous send cancel request.
static uint32_t dm_register_save (DMCONTEXT *dmCtx, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous send save request.
static uint32_t dm_register_cmd_dump (DMCONTEXT *dmCtx, const char *path, DMCONFIG_CALLBACK callback, void *callback_ud)
Asynchonous send dump request.
Detailed Description
This is the user visible API.
Function Documentation
static void dm_context_free (DMCONTEXT * dmCtx) inline static
free a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
Definition at line 1184 of file dmconfig.h.
static struct ev_loop * dm_context_get_ev_loop (DMCONTEXT * dmCtx) static
get libev's ev_loop from a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
libev's ev_loop from this context
Definition at line 1294 of file dmconfig.h.
References dmContext::evloop.
Referenced by dm_generic_send_request(), and dm_init_socket().
static struct event_base * dm_context_get_event_base (DMCONTEXT * dmCtx) static
get libev's libevent compatiblity event_base from a socket context
get libev's libevent compatiblity event_base from a socket context, this function is only for source code compatiblity with libevent
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
libev's event_base from this context
Definition at line 1268 of file dmconfig.h.
References dmContext::evloop.
Referenced by dm_generic_register_request(), dm_generic_send_request(), dm_init_socket(), dm_register_connect_callback(), and writeEvent().
static uint32_t dm_context_get_sessionid (DMCONTEXT * dmCtx) inline static
get the session id from a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
Current session id
Definition at line 1236 of file dmconfig.h.
References dmContext::sessionid.
Referenced by Lua_generic_get_sessionid().
static int dm_context_get_socket (DMCONTEXT * dmCtx) inline static
get the socket from a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
Socket
Definition at line 1210 of file dmconfig.h.
References dmContext::socket.
Referenced by dm_register_connect_callback(), dmcontext_events_gc(), and dmcontext_sequential_gc().
static void dm_context_init (DMCONTEXT * dmCtx, struct event_base * base) inline static
initialize a new socket context
Parameters
[in] dmCtx Pointer to socket context to work on
[in] base libev event_base to use for this context
Definition at line 1152 of file dmconfig.h.
References dm_context_set_event_base().
Referenced by dm_context_new(), and Lua_init_eval().
static DMCONTEXT * dm_context_new (void * ctx, struct event_base * base) inline static
allocate and initialize a new socket context
Parameters
[in] dmCtx Pointer to socket context to work on
[in] base libev event_base to use for this context
Definition at line 1166 of file dmconfig.h.
References dm_context_init().
static void dm_context_set_ev_loop (DMCONTEXT * dmCtx, struct ev_loop * loop) inline static
set libev's ev_loop in a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
[in] loop libev's ev_loop to use for this context
Definition at line 1281 of file dmconfig.h.
References dmContext::evloop.
static void dm_context_set_event_base (DMCONTEXT * dmCtx, struct event_base * base) inline static
set libev's libevent compatiblity event_base in a socket context
set libev's libevent compatiblity event_base in a socket context, this function is only for source code compatiblity with libevent
Parameters
[in] dmCtx Pointer to socket context to work on
[in] base libev's event_base to use for this context
Definition at line 1252 of file dmconfig.h.
References dmContext::evloop.
Referenced by dm_context_init().
static void dm_context_set_sessionid (DMCONTEXT * dmCtx, uint32_t sessionid) inline static
set the session id in a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
[in] sessionid New session id
Definition at line 1223 of file dmconfig.h.
References dmContext::sessionid.
Referenced by dm_decode_start_session(), dm_send_end_session(), generic_Lua_callback(), and Lua_generic_set_sessionid().
static void dm_context_set_socket (DMCONTEXT * dmCtx, int socket) inline static
set the socket in a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
[in] socket New socket
Definition at line 1197 of file dmconfig.h.
References dmContext::socket.
Referenced by dm_create_socket(), and Lua_generic_shutdown().
static uint32_t dm_create_socket (DMCONTEXT * dmCtx, int type) inline static
create a socket in a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
[in] type Type of socket (AF_INET or AF_UNIX)
Return values
RC_OK Callback was installed
RC_ERR_CONNECTION Underlying socket was closed or blocking
Definition at line 1310 of file dmconfig.h.
References dm_context_set_socket(), RC_ERR_CONNECTION, and RC_OK.
Referenced by dm_init_socket(), and LUA_SIG().
uint32_t dm_decode_notifications (DIAM_AVPGRP * grp, uint32_t * type, DIAM_AVPGRP ** notify)
process AVP group returned by dm_send|register_get_passive_notifications or received as an active notification callback parameter
Parameters
[in] grp DM_AVPGRP to decode
[in,out] type Pointer to store type of notification
[in,out] notify Pointer to an pointer to put the resuling DM_AVPGRP pointer into,
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1532 of file dmconfig.c.
References AVP_CONTAINER, AVP_NOTIFY_TYPE, code, diam_avpgrp_get_avp(), diam_decode_avpgrp(), diam_get_uint32_avp(), dm_grp_free(), flags, NOTIFY_NOTHING, RC_ERR_ALLOC, RC_ERR_MISC, RC_OK, and vendor_id.
Referenced by Lua_decode_notifications().
uint32_t dm_decode_unknown_as_string (uint32_t type, void * data, size_t len, char ** val)
converts an arbitrary typed AVP data to an ASCII string
Parameters
[in] type Type of AVP to decode
[in] data Pointer to date to decode
[in] len Length of value
[in,out] val Pointer to pointer to store the result in
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1583 of file dmconfig.c.
References AVP_ABSTICKS, AVP_ADDRESS, AVP_BINARY, AVP_BOOL, AVP_COUNTER, AVP_DATE, AVP_ENUM, AVP_ENUMID, AVP_INT32, AVP_INT64, AVP_PATH, AVP_RELTICKS, AVP_STRING, AVP_UINT32, AVP_UINT64, diam_get_address_avp(), diam_get_int32_avp(), diam_get_int64_avp(), diam_get_time_avp(), diam_get_uint32_avp(), diam_get_uint64_avp(), diam_get_uint8_avp(), RC_ERR_ALLOC, RC_ERR_MISC, and RC_OK.
Referenced by Lua_decode_unknown().
uint32_t dm_generic_register_request (DMCONTEXT * dmCtx, uint32_t code, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud)
send an asynchonous request with a list of arguments
Start an asynchonous request and invoke a callback when the operation completes (either with success or error)
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] grp Pointer to request arguments
[in] callback Callback function to invoke
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Callback was installed
RC_ERR_ALLOC Out of memory
Definition at line 389 of file dmconfig.c.
References APP_ID, AVP_CONTAINER, AVP_SESSIONID, build_diam_request(), CMD_FLAG_REQUEST, code, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint32(), dm_context_get_event_base(), dmconfig_debug_level, dump_diam_packet(), endid, commContext::event, hopid, MAX_INT, new_diam_avpgrp(), new_diam_request(), requestInfo::next, RC_ERR_ALLOC, RC_OK, REQUEST_SHALL_WRITE, dmContext::requestlist_head, dmContext::sessionid, dmContext::socket, TIMEOUT_WRITE_REQUESTS, VP_TRAVELPING, dmContext::writeCtx, and writeEvent().
Referenced by dm_generic_register_request_bool_grp(), dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_register_request_uint32_timeouts(), dm_generic_send_request(), dm_register_add_instance(), dm_register_cancel(), dm_register_commit(), dm_register_end_session(), dm_register_find_instance(), dm_register_get_cfg_session_info(), dm_register_get_passive_notifications(), dm_register_get_session_info(), dm_register_list(), dm_register_packet_get(), dm_register_packet_set(), dm_register_save(), dm_register_subscribe_notify(), dm_register_unsubscribe_notify(), and Lua_generic_register().
uint32_t dm_generic_register_request_bool_grp (DMCONTEXT * dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud)
send an compound asynchonous request, first argument is a boolean
Start an asynchonous request where the first argument is a boolean, invoke a callback when the operation completes (either with success or error)
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] bool First request argument, must be a boolean
[in] grp Pointer to more request arguments
[in] callback Callback function to invoke
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Callback was installed
RC_ERR_ALLOC Out of memory
Definition at line 486 of file dmconfig.c.
References AVP_BOOL, AVP_CONTAINER, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint8(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_packet_param_notify(), and dm_register_recursive_param_notify().
uint32_t dm_generic_register_request_char_address (DMCONTEXT * dmCtx, uint32_t code, const char * str, struct in_addr addr, DMCONFIG_CALLBACK callback, void * callback_ud)
send an compound asynchonous request, only argument is a IP(v4) address
Start an asynchonous request where the only argument is a IP(v4) address invoke a callback when the operation completes (either with success or error)
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] addr Request argument, must be a IP(v4) address
[in] callback Callback function to invoke
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Callback was installed
RC_ERR_ALLOC Out of memory
: extend to IPv6
Definition at line 648 of file dmconfig.c.
References AVP_ADDRESS, AVP_STRING, diam_avpgrp_add_address(), diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
uint32_t dm_generic_register_request_path (DMCONTEXT * dmCtx, uint32_t code, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud)
send an compound asynchonous request, only argument is a data-model path
Start an asynchonous request where the only argument is a data-model path, invoke a callback when the operation completes (either with success or error)
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] path Request argument, must be a valid data-model path
[in] callback Callback function to invoke
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Callback was installed
RC_ERR_ALLOC Out of memory
Definition at line 610 of file dmconfig.c.
References AVP_PATH, diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_cmd_dump(), dm_register_del_instance(), and dm_register_retrieve_enums().
uint32_t dm_generic_register_request_string (DMCONTEXT * dmCtx, uint32_t code, const char * str, DMCONFIG_CALLBACK callback, void * callback_ud)
send an compound asynchonous request, only argument is a string
Start an asynchonous request where the only argument is a string, invoke a callback when the operation completes (either with success or error)
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] str Request argument, must be a string
[in] callback Callback function to invoke
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Callback was installed
RC_ERR_ALLOC Out of memory
Definition at line 573 of file dmconfig.c.
References AVP_STRING, diam_avpgrp_add_string(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_cmd_conf_restore(), and dm_register_cmd_conf_save().
uint32_t dm_generic_register_request_uint32_timeouts (DMCONTEXT * dmCtx, uint32_t code, uint32_t val, struct timeval * timeval1, struct timeval * timeval2, DMCONFIG_CALLBACK callback, void * callback_ud)
send an compound asynchonous request, consisting of an uint32 and two timeouts
Start an asynchonous request where the first argument an uint32 followed by two timeouts, invoke a callback when the operation completes (either with success or error)
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] val First request argument, must be UInt32
[in] timeval1 Second request argument, must be a struct timeval
[in] timeval2 Third request argument, must be a struct timeval
[in] callback Callback function to invoke
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Callback was installed
RC_ERR_ALLOC Out of memory
Definition at line 528 of file dmconfig.c.
References AVP_TIMEOUT_REQUEST, AVP_TIMEOUT_SESSION, AVP_UINT32, diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_register_start_session(), and dm_register_switch_session().
uint32_t dm_generic_send_request (DMCONTEXT * dmCtx, uint32_t code, DIAM_AVPGRP * grp, DIAM_AVPGRP ** ret)
Synchonous request with a list of arguments.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] grp Pointer to request arguments
[in,out] ret Pointer to pointer to put the result into
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 734 of file dmconfig.c.
References dm_context_get_ev_loop(), dm_context_get_event_base(), dm_generic_register_request(), generic_answerHandler(), RC_ERR_CONNECTION, and RC_ERR_MISC.
Referenced by dm_generic_send_request_bool_grp(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_generic_send_request_uint32_timeouts_get_grp(), dm_send_add_instance(), dm_send_cancel(), dm_send_commit(), dm_send_end_session(), dm_send_find_instance(), dm_send_get_cfg_session_info(), dm_send_get_passive_notifications(), dm_send_get_session_info(), dm_send_list(), dm_send_packet_get(), dm_send_packet_set(), dm_send_save(), dm_send_subscribe_notify(), dm_send_unsubscribe_notify(), Lua_generic_request(), and LUA_SIG().
uint32_t dm_generic_send_request_bool_grp (DMCONTEXT * dmCtx, uint32_t code, uint8_t bool, DIAM_AVPGRP * grp)
Synchonous compound request, first argument is a boolean.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] bool First request argument, must be a boolean
[in] grp Pointer to more request arguments
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 773 of file dmconfig.c.
References AVP_BOOL, AVP_CONTAINER, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_uint8(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_send_packet_param_notify(), and dm_send_recursive_param_notify().
uint32_t dm_generic_send_request_char_address_get_char (DMCONTEXT * dmCtx, uint32_t code, const char * str, struct in_addr addr, char ** data)
Synchonous compound request, arguments are a string and an IP(v4) address.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] str First request argument, must be a string
[in] addr Second request argument, must be an IP(v4) address
[in,out] data Pointer to char pointer to put the result string into
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
: extend to IPv6
Definition at line 946 of file dmconfig.c.
References AVP_ADDRESS, AVP_STRING, diam_avpgrp_add_address(), diam_avpgrp_add_string(), dm_decode_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
uint32_t dm_generic_send_request_path_get_char (DMCONTEXT * dmCtx, uint32_t code, const char * path, char ** data)
Synchonous compound request, only argument is a data-model path, return value is a single string.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] path Request argument, must be a valid data-model path
[in,out] data Pointer to char pointer to put the result string into
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 918 of file dmconfig.c.
References dm_decode_string(), dm_generic_send_request_path_get_grp(), and dm_grp_free().
Referenced by dm_send_cmd_dump().
uint32_t dm_generic_send_request_path_get_grp (DMCONTEXT * dmCtx, uint32_t code, const char * path, DIAM_AVPGRP ** answer)
Synchonous compound request, only argument is a data-model path.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] path Request argument, must be a valid data-model path
[in,out] answer Pointer to pointer to put the result into
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 882 of file dmconfig.c.
References AVP_PATH, diam_avpgrp_add_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_generic_send_request_path_get_char(), dm_send_del_instance(), and dm_send_retrieve_enums().
uint32_t dm_generic_send_request_string (DMCONTEXT * dmCtx, uint32_t code, const char * str)
Synchonous compound request, only argument is a string.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] str Request argument, must be a string
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 852 of file dmconfig.c.
References AVP_STRING, diam_avpgrp_add_string(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by dm_send_cmd_conf_restore(), and dm_send_cmd_conf_save().
uint32_t dm_generic_send_request_uint32_timeouts_get_grp (DMCONTEXT * dmCtx, uint32_t code, uint32_t val, struct timeval * timeval1, struct timeval * timeval2, DIAM_AVPGRP ** ret)
Synchonous compound request, consisting of an uint32 and two timeouts.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] code Request code
[in] val First request argument, must be UInt32
[in] timeval1 Second request argument, must be a struct timeval
[in] timeval2 Third request argument, must be a struct timeval
[in,out] ret Pointer to pointer to put the result into
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 807 of file dmconfig.c.
References AVP_TIMEOUT_REQUEST, AVP_TIMEOUT_SESSION, AVP_UINT32, diam_avpgrp_add_timeval(), diam_avpgrp_add_uint32(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_send_start_session(), and dm_send_switch_session().
static void dm_grp_free (DIAM_AVPGRP * grp) inline static
free AVP group
Parameters
[in] grp pointer to DM_AVPGRP to free
Definition at line 554 of file dmconfig.h.
Referenced by dm_decode_node_list(), dm_decode_notifications(), dm_generic_register_request_bool_grp(), dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_register_request_uint32_timeouts(), dm_generic_send_request_bool_grp(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_generic_send_request_uint32_timeouts_get_grp(), dm_grp_set(), dm_grp_set_addr(), dm_register_add_instance(), dm_register_list(), dm_register_recursive_param_notify(), dm_send_add_instance(), dm_send_get_cfg_session_info(), dm_send_get_session_info(), dm_send_list(), dm_send_recursive_param_notify(), dm_send_start_session(), Lua_decode_list(), Lua_decode_notifications(), LUA_SIG(), and LUA_SIG_REGISTER().
static uint32_t dm_grp_get_absticks (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET absticks packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the absticks value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 769 of file dmconfig.h.
References AVP_ABSTICKS, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_addr (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET IP(v4)address packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the IP(v4)address value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 733 of file dmconfig.h.
References AVP_ADDRESS, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_binary (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET binary packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the binary value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 823 of file dmconfig.h.
References AVP_BINARY, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_bool (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET boolean packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name to the boolean value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 570 of file dmconfig.h.
References AVP_BOOL, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_counter (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET counter packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the counter value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 660 of file dmconfig.h.
References AVP_COUNTER, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_date (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET date packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the date value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 751 of file dmconfig.h.
References AVP_DATE, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_enum (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET enum packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the enum value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 697 of file dmconfig.h.
References AVP_ENUM, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_enumid (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET emun id packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the enum id value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 679 of file dmconfig.h.
References AVP_ENUMID, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_int32 (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET Int32 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the Int32 value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 588 of file dmconfig.h.
References AVP_INT32, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_int64 (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET Int64 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the Int64 value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 624 of file dmconfig.h.
References AVP_INT64, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_path (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET path packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the path value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 805 of file dmconfig.h.
References AVP_PATH, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_relticks (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET relticks packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the relticks value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 787 of file dmconfig.h.
References AVP_RELTICKS, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_string (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET string packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the string value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 715 of file dmconfig.h.
References AVP_STRING, AVP_TYPE_PATH, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_uint32 (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET UInt32 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the UInt32 value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 606 of file dmconfig.h.
References AVP_TYPE_PATH, AVP_UINT32, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_uint64 (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET UInt64 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the Int64 value to get
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 642 of file dmconfig.h.
References AVP_TYPE_PATH, AVP_UINT64, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static uint32_t dm_grp_get_unknown (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for GET any packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the value to get, can be of any type
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 841 of file dmconfig.h.
References AVP_TYPE_PATH, AVP_UNKNOWN, diam_avpgrp_add_uint32_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
static DIAM_AVPGRP * dm_grp_new (void) inline static
allocate new AVP group
Return values
pointer to newly allocate DM_AVPGRP
Definition at line 542 of file dmconfig.h.
References new_diam_avpgrp().
Referenced by dm_generic_register_request_bool_grp(), dm_generic_register_request_char_address(), dm_generic_register_request_path(), dm_generic_register_request_string(), dm_generic_register_request_uint32_timeouts(), dm_generic_send_request_bool_grp(), dm_generic_send_request_char_address_get_char(), dm_generic_send_request_path_get_grp(), dm_generic_send_request_string(), dm_generic_send_request_uint32_timeouts_get_grp(), dm_register_add_instance(), dm_register_list(), dm_register_recursive_param_notify(), dm_send_add_instance(), dm_send_list(), dm_send_recursive_param_notify(), Lua_build_get_grp(), Lua_build_param_notify_grp(), Lua_build_set_grp(), LUA_SIG(), and LUA_SIG_REGISTER().
static uint32_t dm_grp_param_notify (DIAM_AVPGRP ** grp, const char * name) inline static
build AVP group for param notify packets
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the paramter
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1136 of file dmconfig.h.
References AVP_PATH, diam_avpgrp_add_string(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by Lua_build_param_notify_grp().
uint32_t dm_grp_set (DIAM_AVPGRP ** grp, const char * name, int type, void * value, size_t size)
build AVP group for SET packet
Parameters
[in,out] grp Pointer to a DM_AVPGRP pointer to put the result into
[in] name Name (path) of config parameter to set
[in] type Type of config parameter to set
[in] value Pointer to value to set
[in] size Length of value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1320 of file dmconfig.c.
References AVP_CONTAINER, AVP_PATH, diam_avpgrp_add_avpgrp(), diam_avpgrp_add_raw(), diam_avpgrp_add_string(), dm_grp_free(), new_diam_avpgrp(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by dm_grp_set_absticks(), dm_grp_set_binary(), dm_grp_set_bool(), dm_grp_set_date(), dm_grp_set_enum(), dm_grp_set_enumid(), dm_grp_set_int32(), dm_grp_set_int64(), dm_grp_set_path(), dm_grp_set_relticks(), dm_grp_set_string(), dm_grp_set_uint32(), dm_grp_set_uint64(), dm_grp_set_unknown(), and Lua_encode_value().
static uint32_t dm_grp_set_absticks (DIAM_AVPGRP ** grp, const char * name, int64_t value) inline static
build AVP group for SET absticks packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the absticks value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1050 of file dmconfig.h.
References AVP_ABSTICKS, dm_grp_set(), and htonll.
static uint32_t dm_grp_set_addr (DIAM_AVPGRP ** grp, const char * name, struct in_addr addr) inline static
build AVP group for SET IP(v4) address packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the IP(v4) address value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1003 of file dmconfig.h.
References AVP_ADDRESS, AVP_CONTAINER, AVP_PATH, diam_avpgrp_add_address(), diam_avpgrp_add_avpgrp(), diam_avpgrp_add_string(), dm_grp_free(), new_diam_avpgrp(), RC_ERR_ALLOC, RC_OK, and VP_TRAVELPING.
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_binary (DIAM_AVPGRP ** grp, const char * name, void * data, size_t len) inline static
build AVP group for SET binary packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the binary value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1103 of file dmconfig.h.
References AVP_BINARY, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_bool (DIAM_AVPGRP ** grp, const char * name, uint8_t value) inline static
build AVP group for SET boolean packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the boolean value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 862 of file dmconfig.h.
References AVP_BOOL, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_date (DIAM_AVPGRP ** grp, const char * name, time_t value) inline static
build AVP group for SET date packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the date value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1032 of file dmconfig.h.
References AVP_DATE, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_enum (DIAM_AVPGRP ** grp, const char * name, const char * value) inline static
build AVP group for SET enum packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the enum value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 969 of file dmconfig.h.
References AVP_ENUM, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_enumid (DIAM_AVPGRP ** grp, const char * name, int32_t value) inline static
build AVP group for SET enum id packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the enum id value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 951 of file dmconfig.h.
References AVP_ENUMID, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_int32 (DIAM_AVPGRP ** grp, const char * name, int32_t value) inline static
build AVP group for SET Int32 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the Int32 value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 879 of file dmconfig.h.
References AVP_INT32, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_int64 (DIAM_AVPGRP ** grp, const char * name, int64_t value) inline static
build AVP group for SET Int64 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the Int64 value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 915 of file dmconfig.h.
References AVP_INT64, dm_grp_set(), and htonll.
static uint32_t dm_grp_set_path (DIAM_AVPGRP ** grp, const char * name, const char * path) inline static
build AVP group for SET path packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the path value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1086 of file dmconfig.h.
References AVP_PATH, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_relticks (DIAM_AVPGRP ** grp, const char * name, int64_t value) inline static
build AVP group for SET relticks packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the relticks value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1068 of file dmconfig.h.
References AVP_RELTICKS, dm_grp_set(), and htonll.
static uint32_t dm_grp_set_string (DIAM_AVPGRP ** grp, const char * name, const char * value) inline static
build AVP group for SET string packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the string value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 986 of file dmconfig.h.
References AVP_STRING, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_uint32 (DIAM_AVPGRP ** grp, const char * name, uint32_t value) inline static
build AVP group for SET UInt32 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the UInt32 value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 897 of file dmconfig.h.
References AVP_UINT32, and dm_grp_set().
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_uint64 (DIAM_AVPGRP ** grp, const char * name, uint64_t value) inline static
build AVP group for SET UInt64 packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the UInt64 value to set
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 933 of file dmconfig.h.
References AVP_UINT64, dm_grp_set(), and htonll.
Referenced by Lua_encode_value().
static uint32_t dm_grp_set_unknown (DIAM_AVPGRP ** grp, const char * name, const char * value) inline static
build AVP group for SET any packet
Parameters
[in,out] grp pointer to DM_AVPGRP to modify
[in] name Name of the value to set, can be of any tpye
[in] value Set named variable to this value
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1120 of file dmconfig.h.
References AVP_UNKNOWN, and dm_grp_set().
Referenced by Lua_encode_value().
uint32_t dm_init_socket (DMCONTEXT * dmCtx, int type)
create a new DM socket in a given context
Create a new blocking socket in a context with default settings
Parameters
[in] dmCtx Pointer to socket context to work on
[in] type Type of socket (AF_INET or AF_UNIX)
Return values
RC_OK Socket created
RC_ERR_MISC Something unexpected happened
RC_ERR_ALLOC Out of memory
Definition at line 687 of file dmconfig.c.
References dm_context_get_ev_loop(), dm_context_get_event_base(), dm_create_socket(), dm_register_connect_callback(), generic_connectHandler(), and RC_ERR_MISC.
Referenced by LUA_SIG().
uint32_t dm_register_add_instance (DMCONTEXT * dmCtx, const char * path, uint16_t instance, DMCONFIG_CALLBACK callback, void * callback_ud)
Asynchonous add an object instance.
Add a new instance of the given object, the path argument must refer to a valid multi instance object, invoke callback on completion
Parameters
[in] dmCtx Pointer to socket context to work on
[in] path Path of the object to instanciate, must be a valid data-model path
[in,out] instance Pointer to an UInt16 to put the create instance Id into
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1465 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_ADDINSTANCE, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_cancel (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous send cancel request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 2077 of file dmconfig.h.
References CMD_DB_CANCEL, and dm_generic_register_request().
static uint32_t dm_register_cmd_dump (DMCONTEXT * dmCtx, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous send dump request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 2114 of file dmconfig.h.
References CMD_DB_DUMP, and dm_generic_register_request_path().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_commit (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous send commit request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 2058 of file dmconfig.h.
References CMD_DB_COMMIT, and dm_generic_register_request().
uint32_t dm_register_connect_callback (DMCONTEXT * dmCtx, int type, DMCONFIG_CONNECT_CALLBACK callback, void * userdata)
start an asynchonous connect
Start an asynchonous connect and invoke a callback when the operation completes (either with success or error)
Parameters
[in] dmCtx Pointer to socket context to work on
[in] type Type of socket (AF_INET or AF_UNIX)
[in] callback Callback function to invoke
[in] userdata Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Callback was installed
RC_ERR_CONNECTION Underlying socket was closed or blocking
RC_ERR_ALLOC Out of memory
Definition at line 304 of file dmconfig.c.
References conneventCtx::callback, connectEvent(), dm_context_get_event_base(), dm_context_get_socket(), conneventCtx::dmCtx, conneventCtx::event, flags, RC_ERR_ALLOC, RC_ERR_CONNECTION, RC_OK, SERVER_IP, SERVER_LOCAL, SERVER_PORT, TIMEOUT_WRITE_REQUESTS, and conneventCtx::user_data.
Referenced by dm_init_socket(), and LUA_SIG_REGISTER().
static uint32_t dm_register_del_instance (DMCONTEXT * dmCtx, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous delete instance request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] path Instance to delete, must be a valid data-model path
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1840 of file dmconfig.h.
References CMD_DB_DELINSTANCE, and dm_generic_register_request_path().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_end_session (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous send session end request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1999 of file dmconfig.h.
References CMD_ENDSESSION, and dm_generic_register_request().
static uint32_t dm_register_find_instance (DMCONTEXT * dmCtx, const char * path, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous find instance request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] path Instance to search in, must be a valid data-model path
[in] grp DM_AVPGRP with the value specification to search
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1861 of file dmconfig.h.
References AVP_PATH, CMD_DB_FINDINSTANCE, diam_avpgrp_add_string(), dm_generic_register_request(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_get_cfg_session_info (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous get config session info request.
Retrieves session id, flags and timeout for this session
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1820 of file dmconfig.h.
References CMD_CFGSESSIONINFO, and dm_generic_register_request().
static uint32_t dm_register_get_passive_notifications (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous retrieve all pending passive notifications.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1979 of file dmconfig.h.
References CMD_GET_PASSIVE_NOTIFICATIONS, and dm_generic_register_request().
static uint32_t dm_register_get_session_info (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous get session info request.
Retrieves the current flags for this session
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1799 of file dmconfig.h.
References CMD_SESSIONINFO, and dm_generic_register_request().
uint32_t dm_register_list (DMCONTEXT * dmCtx, const char * name, uint16_t level, DMCONFIG_CALLBACK callback, void * callback_ud)
Asynchonous list request.
List a values under a give path up to a given depth, invoke callback on completion
Parameters
[in] dmCtx Pointer to socket context to work on
[in] name Path to start the list at, must be a valid data-model path
[in] level Number of level to recurse into
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions caller has to free the answer afterwards
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1501 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_LIST, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_register_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_packet_get (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous send get end request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] grp Prepared GET request DM_AVPGRP
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 2039 of file dmconfig.h.
References CMD_DB_GET, and dm_generic_register_request().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_packet_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous set notification on a parameter.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] isActiveNotify Unused, present only for backwards compatibility
[in] grp DM_AVPGRP list of parameters to set notify on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1958 of file dmconfig.h.
References CMD_PARAM_NOTIFY, and dm_generic_register_request_bool_grp().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_packet_set (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous send set end request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] grp Prepared SET request DM_AVPGRP
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 2019 of file dmconfig.h.
References CMD_DB_SET, and dm_generic_register_request().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_recursive_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify, const char * path, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous set notification on parameters and all child parameters.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] isActiveNotify Unused, present only for backwards compatibility
[in] path parameter path to start on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1923 of file dmconfig.h.
References AVP_PATH, CMD_RECURSIVE_PARAM_NOTIFY, diam_avpgrp_add_string(), dm_generic_register_request_bool_grp(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_retrieve_enums (DMCONTEXT * dmCtx, const char * name, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous retrieve enums request.
Fetch all possible enum values for a given parameter
Parameters
[in] dmCtx Pointer to socket context to work on
[in] name Parameter to get enums for
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1883 of file dmconfig.h.
References CMD_DB_RETRIEVE_ENUMS, and dm_generic_register_request_path().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_save (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous send save request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 2096 of file dmconfig.h.
References CMD_DB_SAVE, and dm_generic_register_request().
static uint32_t dm_register_start_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous start session request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] flags Flags for the start session request
[in] timeout_session Idle timeout for this session
[in] timeout_request Request timeout for this session
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1744 of file dmconfig.h.
References CMD_STARTSESSION, and dm_generic_register_request_uint32_timeouts().
Referenced by LUA_SIG_REGISTER().
uint32_t dm_register_subscribe_notify (DMCONTEXT * dmCtx, DMCONFIG_ACTIVE_NOTIFY notify_callback, void * notify_callback_ud, DMCONFIG_CALLBACK callback, void * callback_ud)
Initialize a subscription to active notification.
Initialize a subscribtion to active notification and install a notify callback for them. This is an asynchronous operation, on completion a callback will be invoked
Parameters
[in] dmCtx Pointer to socket context to work on
[in] notify_callback Notification callback to install
[in] notify_callback_ud Pointer to userdata that will be passed to the notification callback funtion
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1430 of file dmconfig.c.
References dmContext::_dmContext_callbacks::active_notification, dmContext::_dmContext_callbacks::_callback_active_notification::callback, dmContext::callbacks, CMD_SUBSCRIBE_NOTIFY, dm_generic_register_request(), RC_OK, and dmContext::_dmContext_callbacks::_callback_active_notification::user_data.
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_switch_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous switch session request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] flags Flags for the switch session request
[in] timeout_session Idle timeout for this session
[in] timeout_request Request timeout for this session
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1773 of file dmconfig.h.
References CMD_SWITCHSESSION, and dm_generic_register_request_uint32_timeouts().
Referenced by LUA_SIG_REGISTER().
static uint32_t dm_register_unsubscribe_notify (DMCONTEXT * dmCtx, DMCONFIG_CALLBACK callback, void * callback_ud) inline static
Asynchonous unsubscribe from all notifications request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] callback Callback function to invoke on completion
[in] callback_ud Pointer to userdata that will be passed to the callback funtions
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1902 of file dmconfig.h.
References CMD_UNSUBSCRIBE_NOTIFY, and dm_generic_register_request().
Referenced by LUA_SIG_REGISTER().
uint32_t dm_send_add_instance (DMCONTEXT * dmCtx, const char * path, uint16_t * instance)
Synchonous add instance request.
Add a new instance of the given object, the path argument must refer to a valid multi instance object
Parameters
[in] dmCtx Pointer to socket context to work on
[in] path Path of the object to instanciate, must be a valid data-model path
[in,out] instance Pointer to an UInt16 to put the create instance Id into
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1353 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_ADDINSTANCE, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_decode_add_instance(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_cancel (DMCONTEXT * dmCtx) inline static
Synchonous send cancel request.
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1683 of file dmconfig.h.
References CMD_DB_CANCEL, and dm_generic_send_request().
static uint32_t dm_send_cmd_dump (DMCONTEXT * dmCtx, const char * path, char ** data) inline static
Synchonous send dump request.
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1713 of file dmconfig.h.
References CMD_DB_DUMP, and dm_generic_send_request_path_get_char().
Referenced by LUA_SIG().
static uint32_t dm_send_commit (DMCONTEXT * dmCtx) inline static
Synchonous send commit request.
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1668 of file dmconfig.h.
References CMD_DB_COMMIT, and dm_generic_send_request().
static uint32_t dm_send_del_instance (DMCONTEXT * dmCtx, const char * path) inline static
Synchonous delete instance request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] path Instance to delete, must be a valid data-model path
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1459 of file dmconfig.h.
References CMD_DB_DELINSTANCE, and dm_generic_send_request_path_get_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_end_session (DMCONTEXT * dmCtx) inline static
Synchonous send session end request.
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1614 of file dmconfig.h.
References CMD_ENDSESSION, dm_context_set_sessionid(), dm_generic_send_request(), and RC_OK.
Referenced by LUA_SIG().
static uint32_t dm_send_find_instance (DMCONTEXT * dmCtx, const char * path, DIAM_AVPGRP * grp, uint16_t * inst) inline static
Synchonous find instance request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] path Instance to search in, must be a valid data-model path
[in] grp DM_AVPGRP with the value specification to search
[out] inst Id of the found instance
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1478 of file dmconfig.h.
References AVP_PATH, CMD_DB_FINDINSTANCE, diam_avpgrp_add_string(), dm_decode_find_instance(), dm_generic_send_request(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_get_cfg_session_info (DMCONTEXT * dmCtx, uint32_t * sessionid, uint32_t * flags, struct timeval * timeout) inline static
Synchonous get config session info request.
Retrieves session id, flags and timeout for this session
Parameters
[in] dmCtx Pointer to socket context to work on
[in,out] sessionid Session Id
[in,out] flags Flags
[in,out] timeout Session timeout
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1435 of file dmconfig.h.
References CMD_CFGSESSIONINFO, dm_decode_get_cfg_session_info(), dm_generic_send_request(), and dm_grp_free().
Referenced by LUA_SIG().
static uint32_t dm_send_get_passive_notifications (DMCONTEXT * dmCtx, DIAM_AVPGRP ** answer) inline static
Synchonous retrieve all pending passive notifications.
Parameters
[in] dmCtx Pointer to socket context to work on
[in,out] answer DM_AVPGRP to return the pending notifications
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1583 of file dmconfig.h.
References CMD_GET_PASSIVE_NOTIFICATIONS, and dm_generic_send_request().
Referenced by LUA_SIG().
static uint32_t dm_send_get_session_info (DMCONTEXT * dmCtx, uint32_t * flags) inline static
Synchonous get session info request.
Retrieves the current flags for this session
Parameters
[in] dmCtx Pointer to socket context to work on
[in,out] flags Flags
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1407 of file dmconfig.h.
References CMD_SESSIONINFO, dm_decode_get_session_info(), dm_generic_send_request(), and dm_grp_free().
uint32_t dm_send_list (DMCONTEXT * dmCtx, const char * name, uint16_t level, DIAM_AVPGRP ** answer)
Synchonous list request.
List a values under a give path up to a given depth
Parameters
[in] dmCtx Pointer to socket context to work on
[in] name Path to start the list at, must be a valid data-model path
[in] level Number of level to recurse into
[in,out] answer Pointer to an pointer to put the resuling DM_AVPGRP pointer into, caller has to free the answer afterwards
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1391 of file dmconfig.c.
References AVP_PATH, AVP_UINT16, CMD_DB_LIST, diam_avpgrp_add_string(), diam_avpgrp_add_uint16(), dm_generic_send_request(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_packet_get (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp, DIAM_AVPGRP ** answer) inline static
Synchonous send get end request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] grp Prepared GET request DM_AVPGRP
[in,out] answer DM_AVPGRP to return the paramters
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1653 of file dmconfig.h.
References CMD_DB_GET, and dm_generic_send_request().
Referenced by LUA_SIG().
static uint32_t dm_send_packet_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify __attribute__(unused), DIAM_AVPGRP * grp) inline static
Synchonous set notification on a parameter.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] isActiveNotify Unused, present only for backwards compatibility
[in] grp DM_AVPGRP list of parameters to set notify on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1565 of file dmconfig.h.
References CMD_PARAM_NOTIFY, and dm_generic_send_request_bool_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_packet_set (DMCONTEXT * dmCtx, DIAM_AVPGRP * grp) inline static
Synchonous send set end request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] grp Prepared SET request DM_AVPGRP
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1636 of file dmconfig.h.
References CMD_DB_SET, and dm_generic_send_request().
Referenced by LUA_SIG().
static uint32_t dm_send_recursive_param_notify (DMCONTEXT * dmCtx, uint8_t isActiveNotify __attribute__(unused), const char * path) inline static
Synchonous set notification on parameters and all child parameters.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] isActiveNotify Unused, present only for backwards compatibility
[in] path parameter path to start on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1535 of file dmconfig.h.
References AVP_PATH, CMD_RECURSIVE_PARAM_NOTIFY, diam_avpgrp_add_string(), dm_generic_send_request_bool_grp(), dm_grp_free(), dm_grp_new(), RC_ERR_ALLOC, and VP_TRAVELPING.
Referenced by LUA_SIG().
static uint32_t dm_send_retrieve_enums (DMCONTEXT * dmCtx, const char * name, DIAM_AVPGRP ** answer) inline static
Synchonous retrieve enums request.
Fetch all possible enum values for a given parameter
Parameters
[in] dmCtx Pointer to socket context to work on
[in] name Parameter to get enums for
[in,out] answer DM_AVPGRP to return the enums
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1502 of file dmconfig.h.
References CMD_DB_RETRIEVE_ENUMS, and dm_generic_send_request_path_get_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_save (DMCONTEXT * dmCtx) inline static
Synchonous send save request.
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1698 of file dmconfig.h.
References CMD_DB_SAVE, and dm_generic_send_request().
static uint32_t dm_send_start_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request) inline static
Synchonous start session request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] flags Flags for the start session request
[in] timeout_session Idle timeout for this session
[in] timeout_request Request timeout for this session
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1349 of file dmconfig.h.
References CMD_STARTSESSION, dm_decode_start_session(), dm_generic_send_request_uint32_timeouts_get_grp(), and dm_grp_free().
Referenced by LUA_SIG().
static uint32_t dm_send_subscribe_notify (DMCONTEXT * dmCtx) inline static
Synchonous subscribe to notifications request.
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1518 of file dmconfig.h.
References CMD_SUBSCRIBE_NOTIFY, and dm_generic_send_request().
static uint32_t dm_send_switch_session (DMCONTEXT * dmCtx, uint32_t flags, struct timeval * timeout_session, struct timeval * timeout_request) inline static
Synchonous switch session request.
Parameters
[in] dmCtx Pointer to socket context to work on
[in] flags Flags for the switch session request
[in] timeout_session Idle timeout for this session
[in] timeout_request Request timeout for this session
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1382 of file dmconfig.h.
References CMD_SWITCHSESSION, and dm_generic_send_request_uint32_timeouts_get_grp().
Referenced by LUA_SIG().
static uint32_t dm_send_unsubscribe_notify (DMCONTEXT * dmCtx) inline static
Synchonous unsubscribe from all notifications request.
Parameters
[in] dmCtx Pointer to socket context to work on
Return values
RC_OK Request was successfull
RC_ERR_ALLOC Out of memory
Definition at line 1599 of file dmconfig.h.
References CMD_UNSUBSCRIBE_NOTIFY, and dm_generic_send_request().
static void dm_shutdown_socket (DMCONTEXT * dmCtx) inline static
shut down the socket in a socket context
Parameters
[in] dmCtx Pointer to socket context to work on
Definition at line 1328 of file dmconfig.h.
References dmContext::socket.
Referenced by dmcontext_events_gc(), dmcontext_sequential_gc(), and Lua_generic_shutdown().